In [69]:
import numpy as np
import scipy as sp

In [70]:
a = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [71]:
b = np.r_[3,[2]*2,-1:1:4j]
b

array([ 3.        ,  2.        ,  2.        , -1.        , -0.33333333,
        0.33333333,  1.        ])

In [72]:
c = np.c_[10:20:4j, -1:1:4j, 3:4:4j]
c

array([[ 10.        ,  -1.        ,   3.        ],
       [ 13.33333333,  -0.33333333,   3.33333333],
       [ 16.66666667,   0.33333333,   3.66666667],
       [ 20.        ,   1.        ,   4.        ]])

In [73]:
d = np.mgrid[0:5, -1:1:4j]
print(d)
print(np.isreal(d))
print(np.angle(d))
print(np.unwrap(d))

[[[ 0.          0.          0.          0.        ]
  [ 1.          1.          1.          1.        ]
  [ 2.          2.          2.          2.        ]
  [ 3.          3.          3.          3.        ]
  [ 4.          4.          4.          4.        ]]

 [[-1.         -0.33333333  0.33333333  1.        ]
  [-1.         -0.33333333  0.33333333  1.        ]
  [-1.         -0.33333333  0.33333333  1.        ]
  [-1.         -0.33333333  0.33333333  1.        ]
  [-1.         -0.33333333  0.33333333  1.        ]]]
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
[[[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.      

In [74]:
e = np.ogrid[0:5, 10:20]
e

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [75]:
from numpy import poly1d
p = poly1d([2,4])
print(p)
print(p*p)
print(p.integ(k=4))
print(p.integ(k=6))
print(p.deriv())
p([2,3])

 
2 x + 4
   2
4 x + 16 x + 16
   2
1 x + 4 x + 4
   2
1 x + 4 x + 6
 
2


array([ 8, 10])

In [76]:
#using vectorization
def add_substract(a,b):
    if a > b:
        return a - b
    else:
        return a + b

vec_addsub = np.vectorize(add_substract)

In [77]:
print(add_substract(3,4))
print(vec_addsub([0,3,6,9],[1,3,5,7]))

7
[1 6 1 2]


In [78]:
help(np.unwrap)

Help on function unwrap in module numpy.lib.function_base:

unwrap(p, discont=3.141592653589793, axis=-1)
    Unwrap by changing deltas between values to 2*pi complement.
    
    Unwrap radian phase `p` by changing absolute jumps greater than
    `discont` to their 2*pi complement along the given axis.
    
    Parameters
    ----------
    p : array_like
        Input array.
    discont : float, optional
        Maximum discontinuity between values, default is ``pi``.
    axis : int, optional
        Axis along which unwrap will operate, default is the last axis.
    
    Returns
    -------
    out : ndarray
        Output array.
    
    See Also
    --------
    rad2deg, deg2rad
    
    Notes
    -----
    If the discontinuity in `p` is smaller than ``pi``, but larger than
    `discont`, no unwrapping is done because taking the 2*pi complement
    would only make the discontinuity larger.
    
    Examples
    --------
    >>> phase = np.linspace(0, np.pi, num=5)
    >>> phase[3:

In [79]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [80]:
print(np.linspace(1,10,10))
print(np.logspace(1,10,10))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.00000000e+01   1.00000000e+02   1.00000000e+03   1.00000000e+04
   1.00000000e+05   1.00000000e+06   1.00000000e+07   1.00000000e+08
   1.00000000e+09   1.00000000e+10]


In [81]:
x = np.arange(10)
condlist = [x<3, x>5]
choicelist = [x, x**2]
print(condlist)
print(choicelist)
np.select(condlist, choicelist)

[array([ True,  True,  True, False, False, False, False, False, False, False], dtype=bool), array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)]
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])]


array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81])

In [82]:
from scipy.special import factorial
from scipy.special import comb
factorial(6)
comb(4,2)



6.0

In [83]:
help(comb)

Help on function comb in module scipy.special.basic:

comb(N, k, exact=False, repetition=False)
    The number of combinations of N things taken k at a time.
    
    This is often expressed as "N choose k".
    
    Parameters
    ----------
    N : int, ndarray
        Number of things.
    k : int, ndarray
        Number of elements taken.
    exact : bool, optional
        If `exact` is False, then floating point precision is used, otherwise
        exact long integer is computed.
    repetition : bool, optional
        If `repetition` is True, then the number of combinations with
        repetition is computed.
    
    Returns
    -------
    val : int, ndarray
        The total number of combinations.
    
    See Also
    --------
    binom : Binomial coefficient ufunc
    
    Notes
    -----
    - Array arguments accepted only for exact=False case.
    - If k > N, N < 0, or k < 0, then a 0 is returned.
    
    Examples
    --------
    >>> from scipy.special import comb
    

In [84]:
from scipy.interpolate import interp1d

x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)
f = interp1d(x, y)

In [87]:
import numpy as np
from scipy import linalg
A = np.mat('[1 3 5;2 5 1;2 3 8]')
B = np.mat('[10; 8; 3]')
#X = np.mat('[x y z]')
print(linalg.inv(A)*B)
print(linalg.det(A))

[[-9.28]
 [ 5.16]
 [ 0.76]]
-25.000000000000004


### Numpy Examples


In [90]:
a1 = np.array([1,2,3,4])
print(a1, a1.shape, a1.ndim) # .shape == No. of elements and .ndim == dimension

[1 2 3 4] (4,) 1


In [95]:
b1 = a1.reshape(2,2)
print(b1, b1.shape, b1.ndim)
b1[1][1] = 10
print(b1, b1.shape, b1.ndim)
print(a1, a1.shape, a1.ndim) # Observe here the array "a1" is also changed automatically here

[[ 1  2]
 [ 3 10]] (2, 2) 2
[[ 1  2]
 [ 3 10]] (2, 2) 2
[ 1  2  3 10] (4,) 1


In [100]:
# if need a true copy of the array use .copy() always
c1 = a1.reshape(2,2).copy()
print(c1, c1.shape, c1.ndim)
c1[1][1] = 20
print(c1, c1.shape, c1.ndim)
print(a1, a1.shape, a1.ndim) # observe the value in a1 is not altered but changed in c1 to 20

[[ 1  2]
 [ 3 10]] (2, 2) 2
[[ 1  2]
 [ 3 20]] (2, 2) 2
[ 1  2  3 10] (4,) 1


In [109]:
## multiplication (or any operation) of a number to array will change all of it elements
print(c1)
print(c1*2)
print(c1/2)
print(c1+2)
print(c1-2)
d1 = [1,2,3,4]
print(d1*2) # observe how to list behaves when we apply operations

[[ 1  2]
 [ 3 20]]
[[ 2  4]
 [ 6 40]]
[[  0.5   1. ]
 [  1.5  10. ]]
[[ 3  4]
 [ 5 22]]
[[-1  0]
 [ 1 18]]
[1, 2, 3, 4, 1, 2, 3, 4]


In [115]:
a1[np.array([1,3])]
print(a1>4)
print(a1[a1>4])
a1[a1>4] = 20
print(a1[a1>4])

[False False False  True]
[10]
[20]


In [124]:
a1.clip(2,7) # important function

array([2, 2, 3, 7])

In [120]:
a1

array([ 1,  2,  3, 20])

##Handling nonexisting values

In [135]:
f1 = np.array([1,2,3, np.NAN, 6]) # read from a file a NAN value
print(np.isnan(f1))
print(f1[~np.isnan(f1)])
print(np.mean(f1[~np.isnan(f1)]))

[False False False  True False]
[ 1.  2.  3.  6.]
3.0
